# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: UKWA Crawler Test Site
email: web-archivist@bl.uk
description: > # this means to ignore newlines until "baseurl:"
  A static test site, to run web crawlers against.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://crawl-test-site.webarchive.org.uk" # the base hostname & protocol for your site
twitter_username: UKWebArchive
github_username:  ukwa

# Build settings
markdown: kramdown
